-- ----------------
--     COMANDOS    
-- ----------------

-- COMANDOS EXTRAS
USE THM_BOOKMARKET_DB;
SHOW DATABASES;
SHOW TABLES;
DESCRIBE BOOK_INVENTORY;

-- BANCO DE DADOS
CREATE DATABASE THM_BOOKMARKET_DB;

-- TABELAS
CREATE TABLE BOOK_INVENTORY (
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOOK_NAME VARCHAR(255) NOT NULL,
    PUBLICATION_DATE DATE
);

INSERT INTO BOOKS (ID, NAME, PUBLISHED_DATE, DESCRIPTION) VALUES (1, "ANDROID SECURITY INTERNALS", "2014-10-14", "AN IN-DEPTH GUIDE TO ANDROIDS SECURITY ARCHITECTURE");
UPDATE BOOKS  SET DESCRIPTION = "AN IN-DEPTH GUIDE TO ANDROIDS SECURITY ARCHITECTURE." WHERE ID = 1;
ALTER TABLE BOOK_INVENTORY ADD PAGE_COUNT INT;
DROP DATABASE DATABASE_NAME;
DELETE FROM BOOKS WHERE ID = 1;

-- SELECT

SELECT * FROM BOOKS;
SELECT * FROM BOOKS WHERE NAME="DESIGNING SECURE SOFTWARE";
SELECT * FROM BOOKS WHERE NAME LIKE "%ANDROID%" OR DESCRIPTION LIKE "%IOS%";
SELECT * FROM BOOKS WHERE DESCRIPTION LIKE "%GUIDE%";
SELECT * FROM BOOKS WHERE PUBLISHED_DATE < "2020-01-01";
SELECT * FROM BOOKS WHERE PUBLISHED_DATE > "2020-01-01";
SELECT * FROM BOOKS WHERE PUBLISHED_DATE <= "2021-11-15";
SELECT * FROM BOOKS WHERE PUBLISHED_DATE >= "2021-11-15";
SELECT * FROM BOOKS WHERE PUBLISHED_DATE >= "2021-11-02";
SELECT * FROM BOOKS WHERE DESCRIPTION NOT LIKE "%GUIDE%";
SELECT * FROM BOOKS WHERE CATEGORY!="OFFENSIVE SECURITY";
SELECT * FROM BOOKS WHERE CATEGORY="OFFENSIVE SECURITY" AND NAME="BUG BOUNTY BOOTCAMP";
SELECT * FROM BOOKS WHERE ID BETWEEN 2 AND 4;
SELECT DISTINCT NAME FROM BOOKS;

SELECT NAME, PUBLISHED_DATE FROM BOOKS ORDER BY PUBLISHED_DATE ASC;
SELECT NAME, PUBLISHED_DATE  FROM BOOKS ORDER BY PUBLISHED_DATE DESC;
SELECT NAME, COUNT(*) AS CONTAGEM FROM BOOKS GROUP BY NAME;
SELECT NAME, COUNT(*) AS CONTAGEM FROM BOOKS GROUP BY NAME HAVING NAME LIKE '%HACK%' ORDER BY CONTAGEM DESC;
SELECT NAME, LENGTH(NAME) AS COMP FROM HACKING_TOOLS ORDER BY COMP DESC;
SELECT SUM(AMOUNT) AS SOMA FROM HACKING_TOOLS;
SELECT COUNT(*) AS TOTAL_BOOKS FROM BOOKS;
SELECT CONCAT(NAME, "IS TYPE OF", CATEGORY, " BOOK.") AS BOOK_INFO FROM BOOKS;
SELECT LENGTH(NAME) AS NAME_LENGTH FROM BOOKS;
SELECT SUM(PRICE) AS TOTAL_PRICE FROM BOOKS;
SELECT MAX(PUBLISHED_DATE) FROM BOOKS;
SELECT MIN(PUBLISHED_DATE) FROM BOOKS;
SELECT CATEGORY, GROUP_CONCAT(NAME SEPARATOR ", ") FROM BOOKS GROUP BY CATEGORY;
SELECT GROUP_CONCAT(NAME SEPARATOR " & ") FROM HACKING_TOOLS WHERE AMOUNT NOT LIKE "%0";
SELECT SUBSTRING(PUBLISHED_DATE, 1, 4) AS PUBLISHED_YEAR FROM BOOKS;
